Repository predict-idlab/plotly-resampler, pull requests merged in 2023-07, with the labels that each got.

#233 ♻️ deprecate JupyterDash in favor for updated Dash version
  examples/basic_example.ipynb
  plotly_resampler/figure_resampler/figure_resampler.py
  plotly_resampler/figure_resampler/jupyter_dash_persistent_inline_output.py
  poetry.lock
  pyproject.toml
Labels: enhancement, integration

#244 :fire: multiple y-axes support
  CHANGELOG.md
  examples/README.md
  examples/other_examples.ipynb
  plotly_resampler/figure_resampler/figure_resampler_interface.py
  tests/test_multiple_axes.py
Labels: bug, enhancement

#248 👷 build: create codeql.yml
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  README.md
Labels: enhancement
